apriltag_pose_world:
  # Position of the Tag center in World Frame [x, y, z] in meters
  # Example: Tag is at Origin
  position: [1.0, 1.0, 0.0]
  target_tag_frame_name: "land_mark"

  # Tag id
  target_tag_id: 0

  # Orientation of the Tag in World Frame [Roll, Pitch, Yaw] in Radians
  # Example: Tag is flat on the ground (Z-up), aligned with World X
  # If the tag is flat on the floor, its normal usually points +Z.
  orientation_rpy: [0.0, 0.0, 0.0]
